SistemaGranja-master/Granja/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #url(r'^$', views.hello_world, name='hello'),
    url(r'^granja/$', views.ListarGranja.as_view(), name='listar'),
    url(r'^granja/nuevo/', views.CrearGranja.as_view(), name='crear'),
    url(r'^granja/consultar/', views.ConsultarGranja.as_view(), name='consultar'),
    url(r'^granja/eliminar/', views.EliminarGranja.as_view(), name='eliminar'),
    #url(r'^granja/(?P<pk>[0-9]+)/$', views.granja_detail),
    #url(r'^granja/detalle/(?P<pk>[0-9]+)/$', views.DetalleGranja.as_view(), name='detail'),

    #url(r'^granja//', views.new_granja, name='new'),
]

SistemaGranja-master/InicioSesion/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^salir/$', auth_views.logout, {'next_page':'/'}, name='salir'),
    url(r'^principal/$', views.principal, name='principal'),
    url(r'^', views.InicioSesionView.as_view(), name='autenticar'),
]

SistemaGranja-master/SistemaGranja/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^granja/', include('Granja.urls', namespace='granjas')),
    url(r'^usuario/', include('Usuario.urls', namespace='usuarios')),
    url(r'^', include('InicioSesion.urls',namespace='inicio')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SistemaGranja-master/Granja/models.py
from __future__ import unicode_literals

from django.db import models
from EstadoGranja.models import EstadoGranja
from ZonaVida.models import ZonaVida
from Departamento.models import Departamento
from Municipio.models import Municipio

# Create your models here.
class Granja(models.Model):
    id_granja = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)
    id_estado = models.OneToOneField(EstadoGranja, related_name='id_granja_estado',default=None)
    id_departamento = models.OneToOneField(Departamento, related_name='id_granja_departamento',default=None)
    id_municipio = models.OneToOneField(Municipio, related_name='id_granja_municipio',default=None)
    direccion = models.CharField(max_length=50)
    precipitacion = models.DecimalField(max_digits=6,decimal_places=2)
    altitud = models.DecimalField(max_digits=6,decimal_places=2)
    zona_vida = models.OneToOneField(ZonaVida, related_name='id_granja_zonavida',default=None)
    humedad_relativa = models.DecimalField(max_digits=6,decimal_places=2)
    temp_prom = models.DecimalField(max_digits=6,decimal_places=2)
    mapa = models.ImageField(blank=True)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ('id_granja', )

SistemaGranja-master/Granja/forms.py
from django import forms
from .models import Granja

class GranjaForm(forms.ModelForm):
    class Meta:
        model = Granja
        fields = '__all__'

SistemaGranja-master/Granja/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render,get_object_or_404
from django.template import loader

#Decorators
from django.contrib.auth.decorators import login_required

# Class-Based views
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)

from django.core.urlresolvers import reverse_lazy
from .forms import GranjaForm
from .models import Granja

from Usuario.mixins import LoginRequiredMixin

# Create your views here.

#Implementacion de un formulario
# @login_required()
# def new_granja(request):
#     if request.method == 'POST':
#         form = GranjaForm(request.POST, request.FILES)
#         if form.is_valid():
#             granja = form.save()
#             granja.save()
#             return HttpResponseRedirect('/')
#     else:
#         form = GranjaForm()
#
#     template = loader.get_template('new_granja.html')
#     context = {
#         'form' : form
#     }
#     return HttpResponse(template.render(context, request))

class CrearGranja(LoginRequiredMixin, CreateView):
    model = Granja
    success_url = reverse_lazy('granja:listar')
    form_class = GranjaForm

class ListarGranja(ListView):
    model = Granja

class ConsultarGranja(LoginRequiredMixin, DetailView):
    model = Granja

class EliminarGranja(LoginRequiredMixin, DeleteView):
    model = Granja
    success_url = reverse_lazy('granja:listar')

SistemaGranja-master/templates/Granja/granja_detail.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <title>{{ granja.nombre }}</title>
    <link rel="stylesheet" href="{% static 'css/base.css'%}">
  </head>
  <body>
    <h1>{{ granja.nombre }}</h1>
    <img src="{{ granja.mapa.url }}" alt="">
  </body>
</html>

SistemaGranja-master/templates/Granja/granja_list.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <title>Hello World</title>
    <link rel="stylesheet" href="{% static 'css/base.css'%}">
  </head>
  <body>
    <h1 style="color:green">
      Sistema de Granjas
      {% if user.is_authenticated %}
        <h3>{{ user.username }} | <a href="{% url "usuario:salir" %}">Cerrar sesión</a></h3>
      {% else %}
        <a href="{% url "usuario:autenticar" %}">Iniciar Sesión</a>
      {% endif %}
    </h1>
    <a href="{% url "granjas:new" %}">Nueva granja</a>
    <ul>
      {% for gr in object_list %}
      <li>
        <a href="{% url "granjas:detail" gr.id_granja %}">
          {{ gr.nombre }}
        </a>
        <img src="{{ gr.mapa.url }}" alt="">
      </li>
      {% endfor %}
    </ul>
  </body>
</html>